// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/663688ed5e3bc3c7d9c17329
###
GET http://localhost:8080/contacts/663688ed5e3bc3c7d9c1732a
###
GET http://localhost:8080/contacts/663688ed5e3bc3c7d9c1732b

// PRODUCTION Deploy
###
GET https://cse341-w2-personalassignment-1.onrender.com HTTP/1.1
###
GET https://cse341-w2-personalassignment-1.onrender.com/contacts/663688ed5e3bc3c7d9c17329 HTTP/1.1
###
GET https://cse341-w2-personalassignment-1.onrender.com/contacts/663688ed5e3bc3c7d9c1732a HTTP/1.1
###
GET https://cse341-w2-personalassignment-1.onrender.com/contacts/663688ed5e3bc3c7d9c1732b HTTP/1.1
